name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  lint:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.0
      - name: Check Format
        run: zig fmt --check .

  build-and-test:
    name: Test ${{ matrix.project }}
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [lib, server, client]
    steps:
      - uses: actions/checkout@v4
      
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.0

      - name: Build
        run: cd ${{ matrix.project }} && zig build

      - name: Test
        run: cd ${{ matrix.project }} && zig build test
