name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  lint:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.2

      - name: Check Format
        run: |
          find lib client server \
            -type f \
            \( -name '*.zig' -o -name 'build.zig' \) \
            -print0 | xargs -0 zig fmt --check

  build-and-test:
    name: Test ${{ matrix.project }}
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - project: lib
            path: lib
          - project: server
            path: server
          - project: client
            path: client
    defaults:
      run:
        working-directory: ${{ matrix.path }}
    steps:
      - uses: actions/checkout@v4

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.2

      - name: Test
        run: zig build test

      - name: Build
        run: zig build
